import {
  LogIn,
  Eye,
  EyeOff,
  Lock,
  User,
  Hotel,
  LayoutDashboard,
  DoorOpen,
  Calendar,
  CreditCard,
  Users,
  Settings,
  LogOut,
  Menu,
  X,
  Search,
  Filter,
  Plus,
  Edit,
  Trash2,
  Check,
  AlertCircle,
  Info,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  MoreVertical,
  Home,
  BedDouble,
  TrendingUp,
  DollarSign,
  UserCheck,
  Clock,
} from "lucide-react";

export const ICONS = {
  LOGIN: <LogIn />,
  EYE: <Eye />,
  EYE_OFF: <EyeOff />,
  LOCK: <Lock />,
  USER: <User />,
  HOTEL: <Hotel />,
  DASHBOARD: <LayoutDashboard />,
  DOOR_OPEN: <DoorOpen />,
  CALENDAR: <Calendar />,
  CREDIT_CARD: <CreditCard />,
  USERS: <Users />,
  SETTINGS: <Settings />,
  LOGOUT: <LogOut />,
  MENU: <Menu />,
  CLOSE: <X />,
  SEARCH: <Search />,
  FILTER: <Filter />,
  PLUS: <Plus />,
  EDIT: <Edit />,
  TRASH: <Trash2 />,
  CHECK: <Check />,
  ALERT: <AlertCircle />,
  INFO: <Info />,
  CHEVRON_DOWN: <ChevronDown />,
  CHEVRON_RIGHT: <ChevronRight />,
  CHEVRON_LEFT: <ChevronLeft />,
  MORE: <MoreVertical />,
  HOME: <Home />,
  BED_DOUBLE: <BedDouble />,
  TRENDING_UP: <TrendingUp />,
  DOLLAR_SIGN: <DollarSign />,
  USER_CHECK: <UserCheck />,
  CLOCK: <Clock />,
};
